added state machine
EvSedov/TaskManager pull request #9
Opened 2021-05-01 09:05 UTC by EvSedov

2021-05-04 14:06 UTC, Andrew8xx8 requested changes

2021-05-04 14:06 UTC, Andrew8xx8 commented on app/models/task.rb
> +  state_machine :initial => :new_task do
Тут не по стйлгайду хеш указан, надо `initial: :new_task`. Запусти `rubocop -a` внутри контейнера — автоматически все исправит.

2021-05-04 14:06 UTC, Andrew8xx8 commented on app/models/task.rb
> +    event :qa do
Как-то странно называются события. В данном случае должен использовать глагол, который описывает переход. release и archive подходят хорошо, а вот над develop, qa, code_review, ready нужно подумать лучше

2021-05-11 09:10 UTC, greybutton approved these changes

2021-05-12 03:49 UTC, EvSedov commented on app/models/task.rb
> +      transition released: :archived
fixed

2021-05-12 03:50 UTC, merged